---
- name: check for mesos repo list
  stat: path=/etc/apt/sources.list.d/mesosphere.list
  register: list

- name: Add mesosphere repo
  shell: echo "deb http://repos.mesosphere.io/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/mesosphere.list
  when: list.stat.exists == false

- name: Add key
  apt_key:
    keyserver=keyserver.ubuntu.com
    id=E56151BF

- name: apt-get update
  apt: update_cache=yes

- name: Install list of packages
  action: apt pkg={{item}} state=installed
  with_items:
  - mesos
  - marathon
  - deimos
  - curl
  - default-jre
  - python-protobuf
  - python-setuptools
  - zookeeperd

- name: Check mesos default config file
  stat: path=/etc/default/mesos
  register: default_config

- name: Mesos default config file
  template: src=mesos.j2 dest=/etc/default/mesos
  when: default_config.stat.exists == false

- name: check for zookeeper
  stat: path=/var/lib/zookeeper/myid
  register: zookeeper

- name: configure zookeeper
  shell: echo 1 | dd of=/var/lib/zookeeper/myid
  when: zookeeper.stat.exists == false

- name: Check registry
  stat: path=/etc/mesos-master/registry
  register: registry

- name: Configure mesos
  shell: echo in_memory | dd of=/etc/mesos-master/registry
  when: registry.stat.exists == false

- name: Check containerizer_path
  stat: path=/etc/mesos-slave/containerizer_path
  register: containerizer_path

- name: Configure Deimos as a containerizer
  shell: echo /usr/local/bin/deimos | tee /etc/mesos-slave/containerizer_path
  when: containerizer_path.stat.exists == false

- name: Check isolation
  stat: path=/etc/mesos-slave/isolation
  register: isolation

- name: Create mesos-slave isolation
  shell: echo external | tee /etc/mesos-slave/isolation
  when: isolation.stat.exists == false

- name: Delete master script
  file: path=/etc/init/mesos-master.conf state=absent
  when: mesos_role == "master"
  changed_when: false

- name: Delete slave script
  file: path=/etc/init/mesos-slave.conf state=absent
  changed_when: false

- name: Mesos master script
  template: src=mesos-master.j2 dest=/etc/init/mesos-master.conf
  when: mesos_role == "master"
  notify:
    - Restart mesos-master

- name: Mesos slave script
  template: src=mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  notify:
    - Restart mesos-slave
